server:
  port: 9090
spring:
  jpa:
    show-sql: true
  jta:
    enabled: true
    atomikos:
      datasource:
        jta-order:
          xa-properties.url: jdbc:mysql://localhost:3306/order?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
          xa-properties.user: root
          xa-properties.password: 123456
          xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
          unique-resource-name: jta-order
          max-pool-size: 25
          min-pool-size: 3
          max-lifetime: 20000
          borrow-connection-timeout: 10000
        jta-stock:
          xa-properties.url: jdbc:mysql://localhost:3306/stock?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
          xa-properties.user: root
          xa-properties.password: 123456
          xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
          unique-resource-name: jta-stock
          max-pool-size: 25
          min-pool-size: 3
          max-lifetime: 20000
          borrow-connection-timeout: 10000

order:
  id:
    workerId: 0
    datacenterId: 0
