
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
  jmx:
    enabled: false
  application:
    name: dubbo-auto-configuration-consumer-demo
dubbo:
  scan:
    base-packages: com.summer.dubbo.consumer.service
#  protocol:
#    name: dubbo
#    port: 12345
  registry:
    address: zookeeper://localhost:2181
  consumer:
    timeout: 3000
    retries: 3
    version: 1.0.0
server:
  port: 8082
