server:
  undertow:
    direct-buffers: true

grpc:
  enable-reflection: true
  port: 6565

spring:
  datasource:
    url: jdbc:mysql://percona-xtradb-cluster-pxc.operation.svc.cluster.local:3306/board?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: board
    password: board@6789
  jmx:
    enabled: false
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual # 签收模式 AUTO：自动签收；manual：手工签收
        max-concurrency: 10 # 最大并发数
