spring:
  application:
    name: dubbo-auto-configuration-privoder-demo
  datasource:
    url: jdbc:mysql://localhost:3306/order?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
  jmx:
    enabled: false
order:
  id:
    workerId: 0
    datacenterId: 0
logging:
  level:
    com.summer: debug
dubbo:
  scan:
    base-packages: com.summer.dubbo.service
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: N/A
