server:
  undertow:
    direct-buffers: true

grpc:
  enable-reflection: true
  port: 6565

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jmx:
    enabled: false
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
#spring.rabbitmq.publisher-confirms=true
#spring.rabbitmq.publisher-returns=true
#spring.rabbitmq.template.mandatory=true
order:
  id:
    workerId: 0
    datacenterId: 0
