server:
  undertow:
    direct-buffers: true

grpc:
  enable-reflection: true
  port: 6567

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jmx:
    enabled: false
  rabbitmq:
    addresses: 118.178.104.9
    port: 5672
    username: admin
    password: Hzjthl@
    publisher-confirms: true #消息发送到交换机确认机制,是否确认回调 #如果没有本条配置信息，当消费者收到生产者发送的消息后，生产者无法收到确认成功的回调信息
    publisher-returns: true #开启returnedMessage回调函数
    template:
      mandatory: true #必须为true,否则无法触发returnedMessage回调，消息丢失
order:
  id:
    workerId: 0
    datacenterId: 0
