mybatis:
  config-locations: classpath:cfg.xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 50
    default-statement-timeout: 10
    auto-mapping-unknown-column-behavior: WARNING
#logging:
#  level:
#    com.summer: debug