server:
  port: 8080
spring:
  cache:
    type: redis
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_jwt?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678

